### ISSUE TITLE
`ignoreCertificateErrors` ineffective

### ISSUE THREAD

**Issue by bykbtzr** [dneves/gitlab-integration-plugin#10]
Even with `ignoreCertificateErrors` enabled, certificate installed and java security settings reduced I keep getting this error:

```
13:33:30 Error: javax.net.ssl.SSLHandshakeException: You can disable certificate checking by setting ignoreCertificateErrors on GitlabHTTPRequestor. SSL Error: java.security.cert.CertificateException: No name matching mydomain.com found
```

There's an similar [issue in another project](https://github.com/timols/jenkins-gitlab-merge-request-builder-plugin/issues/13) that might help us.

Please let me know if you need further details.

**Comment by chrissnyder2337** [comment]
I am experiencing the same issue.

**Comment by whIzz2000** [comment]
@cvsguimaraes I'm afraid I'm struggling to find where to put/how to generate the certificate to resolve this issue, any hints?

**Comment by chrissnyder2337** [comment]
Shouldn't `ignoreCertificateErrors` ignore any issue with certificates. And should't that include the issue where the identity is not provided because the gitlab installation does not have a signed ssl certificate?

**Comment by chrissnyder2337** [comment]
Even though I have `ignoreCertificateErrors` checked, I still get the following error:

```
javax.net.ssl.SSLHandshakeException: You can disable certificate checking by setting ignoreCertificateErrors on GitlabHTTPRequestor. SSL Error: java.security.cert.CertificateException: No name matching gitlab.utdev.com found
````

**Comment by whIzz2000** [comment]
It should however it looks like the functionality is already in Tools>>tasks and context anyway. Hence the reduced effort on this plug-in. Thanks @dneves for pointing this out

**Comment by cvsguimaraes** [comment]
@whIzz2000 To reproduce this, I've generated a self-signed certificate with a misspelled domain.

**Comment by whIzz2000** [comment]
I could not get around the certificate error and am now using the built-in features of the IDE for issue management and version control instead.

Thanks for the reply

**Comment by kbtzr** [comment]
@tanabarr Hey, sorry to bother. Could you please redact out my name from your latest reply?
