### ISSUE TITLE
Error JsonParseException

### ISSUE THREAD

**Issue by koenhendriks** [dneves/gitlab-integration-plugin#11]
After setting up host and API key i get the following event error:

> Error
> org.codehaus.jackson.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
>          at [Source: java.io.StringReader@5d1dc39d; line: 1, column: 2]

**Comment by GodLesZ** [comment]
Got that too, I think it happens if you use a HTTP url but gitlab is hosted on HTTPS.
At least that was my problem
